#restart.exclude.stable-module=/my-stable-module/(target/classes|build/classes/java/main)/
#restart.exclude.stable-module-jar=/my-stable-module-[^/]+[.]jar

#restart.exclude.demo-domain=/my-stable-module/(target/classes|build/classes/java/main)/
#restart.exclude.mobydex-domain-jar=/mobydex-domain[^/]+[.]jar

restart.exclude.mobydex-domain=.*mobydex-domain.*
